# Netlify configuration file

[functions]
  # Ensure node_modules needed by functions are included
  # included_files = ["node_modules/pdf-parse/**"] # Trying external_node_modules instead

  # Use esbuild bundler and mark pdf-parse as external
  node_bundler = "esbuild"
  external_node_modules = ["pdf-parse"]

# Optional: Specify Node.js version if needed, though Netlify usually uses a compatible one.
# [build.environment]
#   NODE_VERSION = "20" # Or your preferred compatible LTS version
